name: 'Debug'

on:
  workflow_dispatch:

jobs:
  debug:
    strategy:
      fail-fast: false
      matrix:
        label: [ windows-11-arm ]
        arch: [ "386", arm ]

    runs-on: ${{ matrix.label }}

    name: ${{ matrix.arch }} | ${{ matrix.label }}

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'blbrdv/ezstore'
          ref: 'bugfix/old_os_support'
          fetch-depth: 0

      - uses: actions/setup-go@v5
        name: Setup
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Build project
        run: .\run.ps1 --arch ${{ matrix.arch }} build

      - name: Fix Windows 11 shenanigans
        if: matrix.label == 'windows-11-arm'
        run: |
          dism /online /enable-feature /featurename:netfx3 /all
          dism /online /enable-feature /featurename:WCF-HTTP-Activation
          dism /online /enable-feature /featurename:WCF-NonHTTP-Activation

      - name: Run
        run: .\output\${{ matrix.arch }}\bin\ezstore.exe install foo123 --ver 1.0.0 --verbosity d 2>&1;
