name: 'Debug'

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  target:
    runs-on: windows-11-arm
    steps:
      - name: debug
        shell: pwsh
        run: |
          [System.Text.Encoding]::Default;