name: 'Debug'

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  target:
    runs-on: windows-latest
    steps:
      - name: debug
        shell: pwsh
        run: |
          $ProgressPreference = 'Ignore';
          Get-Module -ListAvailable -Name Pester;
          Import-Module -Name Pester -MinimumVersion "5.7.1" -UseWindowsPowerShell 3>$null;
          [PesterConfiguration]::Default;