name: 'Debug'

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  target:
    runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'blbrdv/ezstore'
          ref: 'bugfix/ols_os_support'
          fetch-depth: 0

      - uses: actions/setup-go@v5
        name: Setup
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Build project
        run: .\run.ps1 --arch 386 build

      - name: Run
        run: .\output\386\bin\ezstore.exe install foo123 --ver 1.0.0 --verbosity d 2>&1;
