name: 'Linux full tests'

on:
  workflow_dispatch:
    inputs:
      target-ref:
        description: The branch, tag or SHA to checkout.
        type: string

jobs:
  target:
    runs-on: ubuntu-latest

    outputs:
      target-ref: ${{ steps.ref.outputs.target-ref }}

    steps:
      - name: Setting target ref
        id: ref
        shell: bash
        run: |
          if [ "true" = "${{ inputs.target-ref == '' }}" ]
          then
            ref="main"
          else
            ref="${{ inputs.target-ref }}"
          fi
          
          echo "Ref: $ref"
          echo "target-ref=$ref" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest

    needs: target

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'blbrdv/ezstore'
          ref: ${{ needs.target.outputs.target-ref }}
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Install dependencies
        shell: bash
        run: ./run.sh help &> /dev/null

      - name: Security check
        shell: bash
        run: ./run.sh sec

      - name: Lint project
        shell: bash
        run: ./run.sh lint

      - name: Check code format
        shell: bash
        run: ./run.sh fmt-list

      - name: Run unit tests
        shell: bash
        run: ./run.sh test

      - name: Build project
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: ./run.sh build