name: 'Test'

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        target:
          - label: windows-2025
            name: WIN 10 2025 (x64)
          - label: windows-2022
            name: WIN 10 2022 (x64)
          - label: windows-11-arm
            name: WIN 11 (ARM64)
        include:
          - scenario: install
          - scenario: not-found
            label: windows-2025
          - scenario: no-color
            label: windows-2025

    runs-on: ${{ matrix.target.label }}

    name: Test '${{ matrix.scenario }}' on ${{ matrix.target.name }}

    steps:
      - uses: actions/checkout@v4

#      - name: Download app
#        run: |
#          Invoke-WebRequest -Uri "https://github.com/blbrdv/ezstore/releases/download/v1.3.2/ezstore-portable.7z" -OutFile a.7z
#          7z x a.7z

      - name: Running scenario
        run: .\tests\${{ matrix.scenario }}.ps1
