name: 'Test'

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ windows-2025, windows-2022, windows-11-arm ]
        include:
          - scenario: not-found
            os: windows-2025
          - scenario: no-color
            os: windows-2025
          - scenario: install

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.scenario }} (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v4

#      - name: Download app
#        run: |
#          Invoke-WebRequest -Uri "https://github.com/blbrdv/ezstore/releases/download/v1.3.2/ezstore-portable.7z" -OutFile a.7z
#          7z x a.7z

      - name: Running scenario
        run: .\tests\${{ matrix.scenario }}.ps1
