name: 'Test'

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        target:
          - os: windows-2025
            scenario: install
          - os: windows-2025
            scenario: not-found
          - os: windows-2025
            scenario: no-color
          - os: windows-2022
            scenario: install
          - os: windows-11-arm
            scenario: install

    runs-on: ${{ matrix.target.os }}

    name: ${{ matrix.target.scenario }} (${{ matrix.target.os }})

    steps:
      - uses: actions/checkout@v4

#      - name: Download app
#        run: |
#          Invoke-WebRequest -Uri "https://github.com/blbrdv/ezstore/releases/download/v1.3.2/ezstore-portable.7z" -OutFile a.7z
#          7z x a.7z

      - name: Running scenario
        run: .\tests\${{ matrix.target.scenario }}.ps1
