name: 'Test'

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:

  build:
    runs-on: windows-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - id: set-matrix
        run: |
          echo "matrix={\"include\": [{\"label\": \"windows-latest\", \"name\": \"WINDOWS\", \"scenario\": \"first\", \"id\": \"123\"}]}" >> "$GITHUB_OUTPUT"

  test:
    needs: build

    strategy:
      matrix: ${{ fromJson( needs.build.outputs.matrix ) }}

    runs-on: ${{ matrix.target.label }}

    name: "'${{ matrix.target.scenario }}' on ${{ matrix.target.name }}"

    steps:
      - run: echo "${{ matrix.target.scenario }} ${{ matrix.target.id }}"
