name: 'Test'

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:

  build:
    runs-on: windows-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        run: |
          $Data = Get-Content -Raw '.\.github\matrix.json' | ConvertFrom-Json;
          $Include = @();
          
          foreach ( $Target in $Data.targets ) {
            foreach ( $Os in $Data.os ) {
              if ( $Target.label -eq $Os.label ) {
                $Include += @{
                  label = $Os.label
                  name = "'$($Target.scenario)'on $($Os.name)"
                  run = ".\tests\$($Target.scenario).ps1"
                };
              }
            }
          }
          
          foreach ( $Install in $Data.install ) {
            foreach ( $Os in $Data.os ) {
              $Include += @{
                label = $Os.label
                name = "'$($Install.id)'on $($Os.name)"
                run = ".\tests\install.ps1 $($Install.id)"
              }; 
            }
          }
          
          $Matrix = (@{ include = $Include } | ConvertTo-JSON) -replace '\n';
          $JSON = "matrix=$Matrix";

          echo $JSON;
          echo $JSON | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8;

  test:
    needs: build

    strategy:
      fail-fast: false
      matrix: ${{ fromJson( needs.build.outputs.matrix ) }}

    runs-on: ${{ matrix.label }}

    name: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Download app
        run: |
          Invoke-WebRequest -Uri "https://github.com/blbrdv/ezstore/releases/download/v1.3.3/ezstore-portable.7z" -OutFile a.7z
          7z x a.7z

      - name: Running scenario
        run: ${{ matrix.run }}
